body:
  - type: markdown
    attributes:
      value: |
        # RivEx Dataset Proposal
        Please fill out the form below.
  - type: input
    id: topical_leads
    attributes:
      label: Topical Lead(s)
      description: Enter the GitHub handles of the leads (e.g., @c-h-david)
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Provide a summary of the dataset you are proposing.
    validations:
      required: true
